# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Statistics
author: Gaurav Joshi
logo: img/logo.png
copyright: "2023"
execute:
  execute_notebooks: off

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force

html:
  favicon: img/logo.png
  comments:
    hypothesis: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  # google_analytics_id: G-Z9NNSYF13N

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Gaurav17Joshi/CompStats  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - deflist
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - amsmath

# # Caused Eror as no module named sphinx_proof
# sphinx:
#   extra_extensions:
#     - sphinx_proof